version: '3.3'
services:
  app:
    build: .
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - ./:/code/
      - ../dlopen:/data/

  postgres:
    image: postgres:latest
    environment:
     - POSTGRES_HOST_AUTH_METHOD=trust

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
      - ./static:/var/www/static/
    links:
      - app

  elasticsearch:
    image: launcher.gcr.io/google/elasticsearch2
    volumes:
      - ./elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:

      # RESTful API
      - "9200:9200"

      # Node communication
      - "9300:9300"
