### GENERAL SETTINGS ###

# Site settings
title: "Spack Search"
description: "A static interface to explore Spack Search results."
baseurl: "/spack-search" #important: start with /
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
 syntax_highlighter_opts:
   default_lang: plaintext


permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#159958"
  primary_rgb: "21,153,88" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#F7F7F7"
  link: "#159958"
  link_hover: "#01b2fe"
  footer_heading: "#777"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  packages:
    output: true
    permalink: /package/:path/

url: "https://spack.github.io/spack-search"
repo: "https://github.com/spack/spack-search"
future: true

defaults:
  -
    scope:
      path: "packages"
    values:
      layout: package
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
    future: true

    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "base"


### CONTACT SETTINGS ###

twitter: spackpm


# Search settings
tipue_search:
  include:
    pages: false
    collections: [packages]
  exclude:
    files: [index.md, search.html]

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
